// Farmer GPT backend (generated by ChatGPT)
import express from "express";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config(); // load .env

const app = express();
const PORT = process.env.PORT || 3001;

/** --- CORS --- */
const allowOrigin =
  process.env.FRONTEND_URL || "*"; // set to your site later for tighter security
app.use(
  cors({
    origin: allowOrigin,
  })
);

/** --- Parsers --- */
app.use(express.json({ limit: "1mb" }));

/** --- Root page so Render doesn't show "Not Found" --- */
app.get("/", (_req, res) => {
  res.send(`
    <h1>✅ Farmer GPT Backend is Running</h1>
    <p>Status: OK</p>
    <p>Server Time: ${new Date().toISOString()}</p>
    <p>Health: <a href="/api/health">/api/health</a></p>
  `);
});

/** --- Health check --- */
app.get("/api/health", (_req, res) => {
  res.json({ status: "healthy", by: "ChatGPT" });
});

/** --- Simple echo demo --- */
app.post("/api/echo", (req, res) => {
  res.json({ youSent: req.body, by: "ChatGPT" });
});

/** --- 404 for unknown API routes --- */
app.use((_req, res) => {
  res.status(404).json({ error: "Not found" });
});

/** --- Start server --- */
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
