// Farmer GPT backend (Generated by ChatGPT)
import express from "express";
import cors from "cors";

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.json({ app: "Farmer GPT", status: "ok", by: "ChatGPT", time: new Date().toISOString() });
});

app.get("/api/health", (req, res) => {
  res.json({ status: "healthy", by: "ChatGPT" });
});

app.post("/api/echo", (req, res) => {
  res.json({ youSent: req.body, by: "ChatGPT" });
});

app.listen(PORT, () => {
  console.log(`✅ Backend running at http://localhost:${PORT}`);
});
